### ISSUE TITLE
Not changing versions

### ISSUE THREAD

**Issue by Packjackisback** [rainestorme/chrome100-json#1]
Isn't properly checking for changes, it is now multiple versions behind

**Comment by Packjackisback** [comment]
On further investigation the issue seems to lie in the code itself :( I'm gonna try and fix it, I just hate python

**Comment by Packjackisback** [comment]
The issue is way upstream

**Comment by rainestorme** [comment]
Yes, it is. This downloads the latest sqlite database from the package provided by the Chrome100 devs, but a more scraping-oriented solution might be neccesary.

**Comment by Packjackisback** [comment]
> Yes, it is. This downloads the latest sqlite database from the package provided by the Chrome100 devs, but a more scraping-oriented solution might be neccesary.

Yep. At this point, all the new versions can be found on dash, so there is a small enough amount that we can just keep the json locally and add the ~2 versions manually.

**Comment by rainestorme** [comment]
Manual labor is for chumps... but seriously, it's not that hard to write a scraper - in fact, I'm already almost done with one.

**Comment by rainestorme** [comment]
Should be fixed by 6ec7fd9.

**Comment by Packjackisback** [comment]
Maybe take a look at the release dates for each board? I know it doesn't matter, but it seems counterintuitive to have the wrong dates for everything.

**Comment by rainestorme** [comment]
> Maybe take a look at the release dates for each board? I know it doesn't matter, but it seems counterintuitive to have the wrong dates for everything.

The script could cross-reference `chrome.db`, but the timestamps just aren't able to be ascertained for newer images that aren't synced downstream to `chrome.db`.
